import {mechanism,roadmapMotion} from './guide-motion.mjs';
import {reportDirectory} from './guide-directory.mjs';
import fs from 'node:fs';
import path from 'node:path';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const loadFields=root=>{const dir=path.join(root,'content/guide/fieldnotes');return fs.existsSync(dir)?fs.readdirSync(dir).filter(x=>x.endsWith('.json')).sort().map(x=>JSON.parse(fs.readFileSync(path.join(dir,x),'utf8'))):[]};
const names={llm:['大语言模型','Language models'],vision:['计算机视觉','Computer vision'],generation:['生成模型','Generative models'],multimodal:['多模态','Multimodal learning'],agent:['Agent','Agents'],rl:['强化学习','Reinforcement learning'],'world-model':['世界模型','World models'],embodied:['具身智能','Embodied AI'],systems:['效率与系统','Efficiency & systems'],ai4x:['AI 交叉学科','Interdisciplinary AI']};
const label=(id,lang)=>names[id]?.[lang==='zh'?0:1]||id;
const figures=JSON.parse(fs.readFileSync(new URL('../content/guide/paper-figures.json',import.meta.url),'utf8'));
const figureFor=p=>{
 const fig=figures[p.id];
 if(!fig)throw Error('Missing paper figure '+p.id);
 if(!fs.existsSync(new URL('../public/blog/guide/figures/'+fig.file,import.meta.url)))throw Error('Missing figure asset '+fig.file);
 return fig;
};
export function paperCards(papers,lang){
 const zh=lang==='zh',t=zh?{open:'打开小卡',original:'论文原文',code:'项目 / 代码',close:'关闭',question:'它在解决什么',idea:'核心想法',why:'为什么选这篇',read:'第一遍读哪里',limit:'读完还要问',figure:'论文原图'}:{open:'Open card',original:'Original paper',code:'Project / code',close:'Close',question:'The problem',idea:'The key idea',why:'Why this paper',read:'Where to start',limit:'A question to keep asking',figure:'Figure excerpt from the paper'};
 return `<div class="paper-grid">${papers.map((p,i)=>{const c=p[lang],fig=figureFor(p);return `<div class="paper-item" data-domains="${esc((p.domains||[]).join(' '))}" data-find="${esc(p.title+' '+c.tag+' '+c.question)}"><button class="paper-card" data-paper="${esc(p.id)}" aria-haspopup="dialog"><span class="paper-stamp"><b>${String(i+1).padStart(2,'0')}</b><span>${p.year} · ${esc(c.tag)}</span></span><span class="paper-art"><img src="../figures/${fig.file}" width="${fig.width}" height="${fig.height}" loading="lazy" alt="${esc(p.title+' · '+fig.credit)}"></span><strong>${esc(p.title)}</strong><span class="paper-question">${esc(c.question)}</span><span class="paper-open">${t.open} <b>↗</b></span></button><dialog class="paper-dialog" id="paper-${esc(p.id)}" aria-labelledby="title-${esc(p.id)}"><div class="paper-dialog-head"><span>${p.year} · ${esc(p.venue)}</span><button data-close-paper aria-label="${t.close}">×</button></div><div class="paper-dialog-body"><h2 id="title-${esc(p.id)}">${esc(p.title)}</h2><div class="paper-links"><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${t.original} ↗</a>${p.code?`<a href="${esc(p.code)}" target="_blank" rel="noopener noreferrer">${t.code} ↗</a>`:''}</div>${fig?`<figure class="paper-full-figure"><a href="../figures/${fig.file}" target="_blank"><img src="../figures/${fig.file}" width="${fig.width}" height="${fig.height}" loading="lazy" alt="${esc(p.title+' · '+fig.credit)}"></a><figcaption>${t.figure} · ${esc(fig.credit)} · <a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${t.original}</a></figcaption></figure>`:''}${['question','idea','why','read','limit'].filter(k=>c[k]).map(k=>`<section><h3>${t[k]}</h3><p>${esc(c[k])}</p></section>`).join('')}</div></dialog></div>`}).join('')}</div>`;
}
export function fieldNotes(field,lang,intro,practice){
 const zh=lang==='zh',c=field[lang],heading=(id,text)=>`<h2 id="field-${id}">${text}</h2>`;
 return `<div class="fieldnotes">${intro}${c.overview.map(p=>`<p>${esc(p)}</p>`).join('')}<div class="field-problems"><strong>${zh?'主要任务':'Research tasks'}</strong><ul>${c.solves.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div>${c.stance?`<p class="field-stance">${esc(c.stance)}</p>`:''}${mechanism(field,lang)}${heading('roadmap',zh?'发展路线与代表工作':'Research milestones')}${roadmapMotion(field,lang)}<ol class="field-roadmap">${c.roadmap.map(s=>`<li><span class="road-year">${esc(s.year)}</span><div><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p><div class="road-papers">${s.papers.map(id=>{const p=field.papers.find(p=>p.id===id);if(!p)throw Error('Unknown roadmap paper '+id);return `<a href="#paper-${esc(id)}">${esc(p[lang].tag)} ↗</a>`}).join('')}</div></div></li>`).join('')}</ol>${heading('terms',zh?'关键概念':'Key concepts')}<dl class="field-terms">${c.terms.map(t=>`<div><dt>${esc(t.term)}</dt><dd>${esc(t.text)}</dd></div>`).join('')}</dl><a id="field-practice"></a>${practice}${field.id==='llm'?reportDirectory(lang):''}${heading('papers',zh?'代表论文':'Representative papers')}<p>${esc(c.paperIntro)}</p>${paperCards(field.papers,lang)}${heading('checklist',zh?'入门练习':'Getting started')}<div class="field-checklist">${c.checklist.map((s,i)=>`<label><input type="checkbox" data-check="${field.id}-${i}"><span>${esc(s)}</span></label>`).join('')}</div><p class="field-followup"><a href="ama.html">${zh?'卡在某一步？把过程带到 AMA 一起聊':'Stuck on a step? Bring your attempt to the AMA'} ↗</a></p></div>`;
}
export function paperLibrary(fields,lang){
 const zh=lang==='zh',byId=new Map();for(const f of fields)for(const p of f.papers){if(byId.has(p.id)){byId.get(p.id).domains.push(f.id)}else byId.set(p.id,{...p,domains:[f.id]})}
 const papers=[...byId.values()].sort((a,b)=>a.year-b.year);
 return `<section class="paper-library"><h2 id="paper-library">${zh?'代表作小卡':'Representative papers'}</h2><p>${zh?'先挑一个方向，再选一篇看它怎样提出问题、怎样验证想法。卡片里有短介绍、阅读切入点和原文。':'Choose a field, then a paper: what question did it ask, and how did it test its idea? Each card includes an explanation, a reading starting point, and the original.'}</p><div class="paper-filters"><label>${zh?'方向':'Field'}<select id="paper-domain"><option value="">${zh?'所有方向':'All fields'}</option>${fields.map(f=>`<option value="${f.id}">${esc(label(f.id,lang))}</option>`).join('')}</select></label><label>${zh?'找论文':'Find a paper'}<input id="paper-query" type="search" placeholder="ReAct / diffusion / attention"></label></div><p id="paper-count" aria-live="polite">${papers.length} ${zh?'篇代表作':'papers'}</p>${paperCards(papers,lang)}</section>`;
}
